import fs from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import assert from 'node:assert/strict';
let source=fs.readFileSync('../../supabase/functions/rise-drive/index.ts','utf8').replace(/import \{ createClient \}[^\n]+\n/,'').replace('export async function handler','async function handler').replace('Deno.serve(handler);','');
source=stripTypeScriptTypes(source,{mode:'transform'});
const me='00000000-0000-0000-0000-000000000001';
let role,valid,files,settings,calls;
function reset(){role='student';valid=true;files=[];settings={id:true,folder_id:'folder',enabled:true};calls=[];}
const result=data=>({data,error:null});
function createClient(){return {auth:{getUser:async()=>valid?result({user:{id:me,email_confirmed_at:'now'}}):{data:{user:null},error:{message:'bad token'}}},rpc:async(name,args)=>{calls.push([name,args]);return result(name==='rise_drive_prepare_delete'?true:null);},from(table){let mode='select',where={},payload;const q={select(){return q},eq(k,v){where[k]=v;return q},limit(){return q},upsert(v){mode='upsert';payload=v;return q},update(v){mode='update';payload=v;return q},delete(){mode='delete';return q},single(){return q},maybeSingle(){return q},then(resolve){calls.push([table,mode,where,payload]);let data;if(table==='rise_profiles')data={role};else if(table==='rise_drive_settings'){if(mode==='upsert'&&!settings)settings=payload;if(mode==='update')settings={...settings,...payload};data=settings;}else {data=where.id?files.find(f=>f.id===where.id):files.filter(f=>f.user_id===where.user_id).slice(0,10);}return Promise.resolve(result(data)).then(resolve);}};return q;}};}
async function googleFetch(url,init){calls.push(['http',String(url),init?.method]);if(String(url).includes('oauth2.googleapis.com'))return Response.json({access_token:'private-access'});if(String(url).includes('generateIds'))return Response.json({ids:['newfile']});if(String(url).includes('alt=media'))return new Response('private-file');if(init?.method==='DELETE')return new Response(null,{status:204});return Response.json({id:'folder',mimeType:'application/vnd.google-apps.folder',trashed:false});}
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'server-only',SUPABASE_ANON_KEY:'public',GOOGLE_DRIVE_CLIENT_ID:'client',GOOGLE_DRIVE_CLIENT_SECRET:'secret',GOOGLE_DRIVE_REFRESH_TOKEN:'refresh'};
const handler=new Function('createClient','Deno','fetch',source+';return handler;')(createClient,{env:{get:k=>env[k]}},googleFetch);
function req(action,body={},token='user-token',origin='https://youtingyeh.github.io'){const headers={Origin:origin,Authorization:'Bearer '+token};if(!(body instanceof FormData))headers['Content-Type']='application/json';return new Request('https://example.supabase.co/functions/v1/rise-drive?action='+action,{method:'POST',headers,body:body instanceof FormData?body:JSON.stringify(body)});}
reset();valid=false;assert.equal((await handler(req('initialize'))).status,401);assert(!calls.some(c=>c[0]==='http'));
reset();assert.equal((await handler(req('initialize'))).status,403);assert.equal((await handler(req('initialize',{},'x','https://evil.test'))).status,403);
reset();const fid='10000000-0000-0000-0000-000000000001';files=[{id:fid,user_id:'someone-else',drive_id:'secret-drive-id',status:'ready',original_name:'proof.pdf'}];assert.equal((await handler(req('download',{id:fid}))).status,404);assert(!calls.some(c=>c[0]==='http'));
role='admin';let response=await handler(req('download',{id:fid}));assert.equal(response.status,200);assert.equal(await response.text(),'private-file');assert.equal(response.headers.get('Cache-Control'),'no-store');
reset();role='admin';response=await handler(req('initialize'));assert.equal(response.status,200);assert((await response.json()).folderURL.includes('drive.google.com'));assert(!calls.some(c=>String(c[1]).includes('/permissions')));
reset();let form=new FormData();form.append('file',new File(['<script>alert(1)</script>'],'bad.pdf',{type:'application/pdf'}));assert.equal((await handler(req('upload',form))).status,400);assert(!calls.some(c=>c[0]==='rise_drive_reserve'));
reset();form=new FormData();form.append('file',new File(['%PDF-1.7 test'],'proof.pdf',{type:'application/pdf'}));response=await handler(req('upload',form));assert.equal(response.status,200);const data=await response.json();assert.equal(data.provider,'google-drive');assert(!JSON.stringify(data).includes('private-access'));assert(calls.some(c=>c[0]==='rise_drive_reserve'));assert(calls.some(c=>c[0]==='rise_drive_files'&&c[1]==='update'&&c[3].status==='ready'));
reset();role='admin';assert.equal((await handler(req('purge-mine'))).status,403);
reset();files=[{id:fid,user_id:me,drive_id:'own-file'}];assert.equal((await handler(req('purge-mine'))).status,200);assert(calls.some(c=>c[0]==='rise_drive_files'&&c[1]==='delete'&&c[2].user_id===me));
console.log('PASS: JWT validation, origin filter, admin-only initialization, private downloads, signature checks, upload registration, owner-only cleanup');
