import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
const db=new PGlite();
await db.exec(`create role service_role bypassrls; create role anon; create role authenticated; create schema auth; create schema storage;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to authenticated;
grant execute on function auth.uid() to authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
grant select,insert,delete on storage.objects to authenticated;
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;`);
await db.exec(fs.readFileSync('../../backend/setup.sql','utf8'));
const migration=fs.readFileSync('../../backend/staff-upgrade.sql','utf8');await db.exec(migration);await db.exec(migration);
const driveMigration=fs.readFileSync('../../backend/google-drive.sql','utf8');await db.exec(driveMigration);await db.exec(driveMigration);
await db.exec(fs.readFileSync('../../backend/teaching-resources.sql','utf8'));await db.exec(fs.readFileSync('../../backend/teaching-resources.sql','utf8'));
const ids=[1,2,3,4,5].map(n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0'));
for(const [i,id]of ids.entries())await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())",[id,`u${i}@example.org`]);
for(const [i,role]of [[1,'teacher'],[2,'teacher'],[3,'ta'],[4,'admin']])await db.query('update public.rise_profiles set role=$1 where id=$2',[role,ids[i]]);
async function as(i){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[i]]);await db.exec('set role authenticated');}
async function deny(sql,args=[]){let failed=false;try{await db.query(sql,args);}catch{failed=true;}if(!failed)throw Error('unexpected permission: '+sql);}
const rid='10000000-0000-0000-0000-000000000001';
const path=ids[1]+'/lesson.pdf';
const doc={title:'Lesson',body:'Explanation',summary:'',subject:'math',kind:'material',status:'draft',files:[{path,name:'lesson.pdf',type:'application/pdf'}]};
const save='select public.rise_save_resource($1,$2,$3)';
await as(0);await deny(save,[rid,0,JSON.stringify(doc)]);
await as(3);await deny(save,[rid,0,JSON.stringify(doc)]);
await as(1);await db.query("insert into storage.objects(bucket_id,name) values('rise-teaching-files',$1)",[path]);await db.query(save,[rid,0,JSON.stringify(doc)]);
await as(2);if((await db.query('select * from public.rise_teaching_resources')).rows.length)throw Error('teacher sees peer draft');
await deny(save,[rid,1,JSON.stringify(doc)]);if((await db.query("select * from storage.objects where bucket_id='rise-teaching-files'")).rows.length)throw Error('draft file leak');
await db.exec('reset role;set role anon');if((await db.query('select * from public.rise_teaching_resources')).rows.length)throw Error('public draft leak');
await as(1);doc.status='published';await db.query(save,[rid,1,JSON.stringify(doc)]);await deny(save,[rid,1,JSON.stringify(doc)]);
await as(0);if((await db.query('select * from public.rise_teaching_resources')).rows.length!==1)throw Error('published missing');if((await db.query("select * from storage.objects where bucket_id='rise-teaching-files'")).rows.length!==1)throw Error('published file missing');await db.query('select public.rise_record_resource_visit($1)',[rid]);
await as(3);if((await db.query('select * from public.rise_resource_visits')).rows.length)throw Error('visit leak');
await as(4);doc.status='draft';await db.query(save,[rid,2,JSON.stringify(doc)]);
await as(0);if((await db.query("select * from storage.objects where bucket_id='rise-teaching-files'")).rows.length)throw Error('unpublished file readable');await deny('select public.rise_record_resource_visit($1)',[rid]);
await as(1);await db.exec('reset role');await db.query("update public.rise_profiles set role='student' where id=$1",[ids[1]]);await as(1);await deny(save,[rid,3,JSON.stringify(doc)]);
console.log('PASS roles, ownership, private drafts/files, publication/unpublish, stale version, revoked role, private visit records');await db.close();
