import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
const db=new PGlite();
await db.exec(`create role service_role bypassrls; create role anon; create role authenticated; create schema auth; create schema storage;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to authenticated;
grant execute on function auth.uid() to authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
grant select,insert,delete on storage.objects to authenticated;
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;`);
await db.exec(fs.readFileSync('../../backend/setup.sql','utf8'));
const migration=fs.readFileSync('../../backend/staff-upgrade.sql','utf8');await db.exec(migration);await db.exec(migration);
const driveMigration=fs.readFileSync('../../backend/google-drive.sql','utf8');await db.exec(driveMigration);await db.exec(driveMigration);
await db.exec(fs.readFileSync('../../backend/teaching-resources.sql','utf8'));await db.exec(fs.readFileSync('../../backend/teaching-resources.sql','utf8'));
const placement=fs.readFileSync('../../backend/resource-placement.sql','utf8');await db.exec(placement);await db.exec(placement);
const ids=[1,2,3,4].map(n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0'));
for(const [i,id]of ids.entries())await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())",[id,`u${i}@example.org`]);
for(const [i,role]of [[1,'teacher'],[2,'teacher'],[3,'admin']])await db.query('update public.rise_profiles set role=$1 where id=$2',[role,ids[i]]);
async function as(i){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[i]]);await db.exec('set role authenticated');}
async function deny(sql,args=[]){let failed=false;try{await db.query(sql,args);}catch{failed=true;}if(!failed)throw Error('unexpected allow');}
const rid=n=>'10000000-0000-0000-0000-'+String(n).padStart(12,'0');
const doc={title:'Lesson',body:'Text',subject:'math',kind:'article',status:'published',destination:'science',collection:'Algebra',group_order:10,item_order:0};
await as(1);for(let n=1;n<=20;n++)await db.query('select public.rise_save_resource($1,0,$2)',[rid(n),JSON.stringify({...doc,item_order:n})]);
await db.query('select public.rise_save_resource($1,0,$2)',[rid(21),JSON.stringify({...doc,status:'draft'})]);
await db.exec('reset role;set role anon');
let rows=(await db.query("select * from public.rise_resource_groups('science')")).rows;if(rows.length!==1||Number(rows[0].item_count)!==20)throw Error('batch floods groups or draft leak');
if((await db.query("select * from public.rise_resource_groups('learning')")).rows.length)throw Error('wrong destination');
rows=(await db.query("select * from public.rise_resource_group_items($1,'science','Algebra','math','all',0)",[ids[1]])).rows;if(rows.length!==13||rows[0].id!==rid(1))throw Error('paging/order');
const changes=[{id:rid(1),version:1,position:2},{id:rid(2),version:1,position:1}];
const organize="select public.rise_organize_resources($1,'learning','Unit 1',1)";
await as(0);await deny(organize,[JSON.stringify(changes)]);await as(2);await deny(organize,[JSON.stringify(changes)]);
await as(1);await deny(organize,[JSON.stringify([{...changes[0],version:99},changes[1]])]);
if((await db.query("select * from public.rise_resource_groups('learning')")).rows.length)throw Error('partial update');
await db.query(organize,[JSON.stringify(changes)]);
rows=(await db.query("select * from public.rise_resource_group_items($1,'learning','Unit 1','math')",[ids[1]])).rows;if(rows.length!==2||rows[0].id!==rid(2))throw Error('move/order failed');
await as(2);await db.query('select public.rise_save_resource($1,0,$2)',[rid(22),JSON.stringify(doc)]);
rows=(await db.query("select * from public.rise_resource_groups('science')")).rows;if(rows.length!==2)throw Error('different authors mixed');
await as(3);await db.query(organize,[JSON.stringify([{id:rid(22),version:1,position:1}])]);
console.log('PASS repeated migration, 20 uploads form one group, section isolation, draft exclusion, pagination, atomic bulk ownership/version checks and ordering');await db.close();
