import {PGlite} from '@electric-sql/pglite';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const pg=new PGlite();
await pg.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
create table auth.users(id uuid primary key,email_confirmed_at timestamptz,raw_user_meta_data jsonb);
create table public.rise_profiles(id uuid primary key references auth.users(id) on delete cascade,role text,display_name text);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('app.uid',true),'')::uuid $$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;grant usage on schema auth,storage to authenticated;grant select,insert on storage.objects to authenticated;`);
const sql=await readFile(new URL('../../backend/course-assignments.sql',import.meta.url),'utf8');
await pg.exec(sql);await pg.exec(sql);
const ids=Object.fromEntries(['student','other','ta','teacher','admin','judge','unverified'].map((x,i)=>[x,'00000000-0000-4000-8000-'+String(i+1).padStart(12,'0')]));
for(const [key,id] of Object.entries(ids)){await pg.query('insert into auth.users(id,email_confirmed_at) values($1,$2)',[id,key==='unverified'?null:'2026-01-01']);await pg.query('insert into public.rise_profiles values($1,$2,$3)',[id,key==='other'||key==='unverified'?'student':key==='judge'?'teacher':key,key]);}
async function as(key,fn){await pg.query("select set_config('app.uid',$1,false)",[ids[key]||'']);await pg.exec('set role authenticated');try{return await fn();}finally{await pg.exec('reset role');}}
const act=(key,action,data={})=>as(key,async()=>(await pg.query('select public.rise_workflow_action($1,$2) as result',[action,data])).rows[0].result);
const read=(key,area,id=null)=>as(key,async()=>(await pg.query('select public.rise_workflow_read($1,$2) as result',[area,id])).rows[0].result);
const rejects=async(fn,pattern)=>assert.rejects(fn,pattern);
await rejects(()=>read('unverified','assignments'),/驗證/);
await rejects(()=>as('student',()=>pg.query('select * from rise_work.assignments')),/permission denied/);
await rejects(()=>act('student','assignment_create',{title:'bad',body:'bad',subject:'math'}),/僅教師/);
const assignment=(await act('teacher','assignment_create',{title:'平方展開',body:'說明 (a+b)² 的展開與依據',subject:'math',published:false})).id;
assert.equal((await read('student','assignments')).items.length,0);
await act('teacher','assignment_state',{id:assignment,published:true});
assert.equal((await read('student','assignments')).items.length,1);
const v1=(await act('student','assignment_submit',{id:assignment,expected_version:0,body:'a²+b²',files:[]})).id;
await rejects(()=>act('student','assignment_submit',{id:assignment,expected_version:0,body:'duplicate'}),/版本已更新/);
assert.equal((await read('other','assignment',assignment)).revisions.length,0);
await rejects(()=>act('student','assignment_review',{id:v1}),/僅教學/);
await act('ta','assignment_review',{id:v1,analysis:'少交叉項',improvement:'画面積圖',followup:'a=b=1 會得到什麼？',score:1,outcome:'revise'});
await rejects(()=>act('ta','assignment_review',{id:v1,analysis:'x',improvement:'x',followup:'x',score:5,outcome:'completed'}),/check constraint|unique constraint/);
await rejects(()=>act('student','assignment_submit',{id:assignment,expected_version:1,body:'a²+2ab+b²'}),/修訂時/);
const v2=(await act('student','assignment_submit',{id:assignment,expected_version:1,body:'a²+2ab+b²，長方形面積為 ab，各有兩個',change_note:'補充交叉項和面積圖推理'})).id;
await act('teacher','assignment_review',{id:v2,analysis:'推理完整',improvement:'可加入標記',followup:'三項平方如何展開？',score:4,outcome:'completed'});
assert.equal((await read('student','assignment',assignment)).revisions.length,2);
const metrics=await read('student','analytics');assert.equal(metrics.rows[0].revisions,1);assert.equal(metrics.rows[0].completed,1);assert.equal(metrics.timeline.length,2);
assert.equal((await read('other','analytics')).rows.length,0);
await act('teacher','assignment_state',{id:assignment,closed:true});await rejects(()=>act('student','assignment_submit',{id:assignment,expected_version:2,body:'late',change_note:'x'}),/截止/);
await pg.query("insert into storage.objects(bucket_id,name) values('rise-work-files',$1)",[ids.other+'/private.pdf']);
assert.equal((await as('student',()=>pg.query('select public.rise_work_file_access($1,false) as yes',[ids.other+'/private.pdf']))).rows[0].yes,false);
console.log('PASS assignments: role restrictions, private versions, immutable revisions, stale submit, structured review, metrics, closed state, private files');

const course=(await act('admin','course_create',{title:'試批訓練',body:'完成四項能力練習',published:true})).id;
await rejects(()=>read('student','training'),/限教師/);
const t1=(await act('ta','training_submit',{id:course,expected_version:0,body:'試批作業一'})).id;
await rejects(()=>act('ta','certify',{id:t1,decision:'approved',note:'self'}),/僅管理員/);
await act('admin','certify',{id:t1,decision:'returned',note:'請補充倫理處理'});
const t2=(await act('ta','training_submit',{id:course,expected_version:1,body:'四項已補齊'})).id;
await rejects(()=>act('admin','certify',{id:t1,decision:'approved',note:'old'}),/最新版本/);
await act('admin','certify',{id:t2,decision:'approved',note:'四項通過'});
let training=await read('ta','training');assert.equal(training.certificates[0].decision,'approved');assert(training.certificates[0].valid_until);
assert.equal((await read('admin','analytics')).summary.valid_certifications,1);
await act('admin','certify',{id:t2,decision:'revoked',note:'需重新考核'});training=await read('ta','training');assert.equal(training.certificates[0].decision,'revoked');
assert.equal((await read('admin','analytics')).summary.valid_certifications,0);
assert.equal((await read('teacher','training')).submissions.length,0);
assert.equal((await pg.query('select role from public.rise_profiles where id=$1',[ids.ta])).rows[0].role,'ta');
console.log('PASS training: versioned evidence, admin-only certification, latest version, returns, expiry, revocation, no role mutation');

const contest=(await act('teacher','competition_create',{title:'提問測試賽',body:'背景動機影響',deadline:new Date(Date.now()+86400000).toISOString()})).id;
assert.equal((await read('student','competitions')).items.length,0);
await act('teacher','judge_assign',{id:contest,judge_id:ids.judge});await act('teacher','competition_state',{id:contest,state:'open'});
const e1=(await act('student','competition_submit',{id:contest,expected_version:0,title:'第一版',body:'background',division:'高中',field:'自然科學'})).id;
const e2=(await act('student','competition_submit',{id:contest,expected_version:1,title:'第二版',body:'updated',division:'高中',field:'自然科學'})).id;
assert.equal((await read('other','competition',contest)).own.length,0);
assert.equal((await read('other','competition',contest)).entries.length,0);
await rejects(()=>act('teacher','competition_state',{id:contest,state:'judging'}),/依序/);
await pg.query("update rise_work.competitions set deadline=now()-interval '1 minute' where id=$1",[contest]);
await rejects(()=>act('student','competition_submit',{id:contest,expected_version:2,title:'late',body:'x',division:'高中',field:'自然科學'}),/截止/);
await act('teacher','competition_state',{id:contest,state:'judging'});
await act('teacher','judge_remove',{id:contest,judge_id:ids.judge});
await rejects(()=>act('teacher','competition_state',{id:contest,state:'results'}),/至少一位/);
await act('teacher','judge_assign',{id:contest,judge_id:ids.judge});
const judging=await read('judge','competition',contest);assert.equal(judging.entries.length,1);assert.equal(judging.entries[0].id,e2);assert(!('student_id' in judging.entries[0]));
await rejects(()=>act('teacher','competition_judge',{id:e2}),/無權/);
await rejects(()=>act('judge','competition_judge',{id:e1}),/最終版本/);
await rejects(()=>act('teacher','competition_state',{id:contest,state:'results'}),/尚未完成/);
await act('judge','competition_judge',{id:e2,innovation:4,depth:3,appropriateness:5,inspiration:4,note:'具有探索價值'});
await rejects(()=>act('teacher','judge_remove',{id:contest,judge_id:ids.judge}),/不可移除/);
assert.equal((await read('student','competition',contest)).judgments.length,0);
await act('teacher','competition_state',{id:contest,state:'results'});
const results=await read('student','competition',contest);assert.equal(results.results[0].average,16);assert.equal(results.judgments.length,1);assert(!('judge_id' in results.judgments[0]));
await rejects(()=>act('teacher','competition_state',{id:contest,state:'open'}),/依序/);
console.log('PASS competition: draft privacy, deadline, version lock, assigned judges, anonymized entry, complete scoring before results, no early feedback');
await pg.query('delete from auth.users where id=$1',[ids.teacher]);
assert.equal((await read('admin','assignments')).items[0].owner_id,null);
await rejects(()=>act('judge','assignment_state',{id:assignment,closed:false}),/無權/);
await act('admin','assignment_state',{id:assignment,closed:false});
console.log('PASS staff deletion: teaching records retained, orphan management restricted to admin');



await pg.query('insert into auth.users(id,email_confirmed_at) values($1,now())',[ids.teacher]);
await pg.query("insert into public.rise_profiles values($1,'teacher','teacher')",[ids.teacher]);
const courseAction=(key,action,data={})=>as(key,async()=>(await pg.query('select public.rise_course_action($1,$2) as result',[action,data])).rows[0].result);
await rejects(()=>courseAction('student','save',{title:'非法'}),/僅管理員/);
const classification=(await courseAction('admin','save',{title:'基礎物理',active:true})).id;
await courseAction('student','membership',{course_ids:[classification]});
const targeted=(await act('teacher','assignment_create',{title:'課程作業',body:'推理',subject:'physics',published:true,audience:'courses',course_ids:[classification]})).id;
assert((await read('student','assignments')).items.some(a=>a.id===targeted));
assert(!(await read('other','assignments')).items.some(a=>a.id===targeted));
await rejects(()=>read('other','assignment',targeted),/無權/);
await rejects(()=>act('other','assignment_submit',{id:targeted,expected_version:0,body:'侵入'}),/未指派/);
await act('student','assignment_submit',{id:targeted,expected_version:0,body:'正確'});
assert(!(await read('student','assignments')).items.find(a=>a.id===targeted).course_ids);
await rejects(()=>act('judge','assignment_audience',{id:targeted,audience:'all'}),/無權/);
await rejects(()=>act('teacher','assignment_create',{title:'invalid',body:'x',subject:'math',audience:'courses',course_ids:[]}),/選擇/);
await rejects(()=>courseAction('student','roster',{search:'other'}),/僅教師/);
assert.equal((await courseAction('teacher','roster',{search:'other'}))[0].id,ids.other);
await courseAction('admin','save',{id:classification,title:'基礎物理',active:false});
await rejects(()=>courseAction('other','membership',{course_ids:[classification]}),/停止加入/);
assert((await read('student','assignments')).items.some(a=>a.id===targeted));
await courseAction('student','membership',{course_ids:[]});
await rejects(()=>read('student','assignment',targeted),/無權/);
assert.equal((await read('teacher','assignment',targeted)).revisions.length,1);
await act('teacher','assignment_audience',{id:targeted,audience:'students',student_ids:[ids.other]});
assert((await read('other','assignments')).items.some(a=>a.id===targeted));
await rejects(()=>read('student','assignment',targeted),/無權/);
await courseAction('admin','save',{id:classification,title:'基礎物理',active:true});
const signup='00000000-0000-4000-8000-000000000099';
await pg.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[signup,{course_ids:[classification,'invalid'],role:'admin'}]);
assert.equal((await pg.query('select course_id from rise_work.class_members where user_id=$1',[signup])).rows[0].course_id,classification);
await rejects(()=>as('other',()=>pg.query('select * from rise_work.class_members')),/permission denied/);
await rejects(()=>as('other',()=>pg.query('select rise_work.set_assignment_audience($1,$2)',[targeted,{audience:'all'}])),/permission denied/);
console.log('PASS courses: admin settings, self membership, targeting read/list/submit, no roster leaks, owner-only edits, archived enrollment, history preservation, signup trigger');
await pg.close();
